<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.48.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComicPlate.Core\ComicPlate.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
